- table: user
  columns:
    login: varchar
    email: varchar
  index:
    - login

- table: user_group
  columns:
    user: m2o user.id
    group: m2o group.id
  index:
    - user
    - group

- table: group
  columns:
    name: varchar
  index:
    - name
